- name: Ensure directories exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0644'
  loop:
    - ~/compose
    - ~/compose/uptime-kuma

- name: Ensure docker-compose file has been updated
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/compose/uptime-kuma/
    mode: '0644'
  loop:
    - docker-compose.yml
    - prometheus.yml

- name: Ensure uptime-kuma compose files are up
  community.docker.docker_compose:
    state: present
    project_src: ~/compose/uptime-kuma/
    files:
      - docker-compose.yml