- name: Create prom network
  community.docker.docker_network:
    name: prom

- name: Ensure directories exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0644'
  loop:
    - ~/compose
    - ~/compose/grafana-prom-node

- name: Ensure docker-compose file has been updated
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/compose/grafana-prom-node/
    mode: '0644'
  loop:
    - docker-compose.yml
    - prometheus.yml
    - defaults.ini
    
- name: Ensure grafana-prom-node compose files are up
  community.docker.docker_compose:
    state: present
    project_src: ~/compose/grafana-prom-node/
    files:
      - docker-compose.yml